version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hospital-db
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
    ports:
      - "1433:1433"
    volumes:
      - hospitaldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "exit 0"] 
      interval: 10s
      retries: 10
      start_period: 20s

       

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: hospital-db-init
    depends_on:
      - db
    volumes:
      - ./init.sql:/init.sql
    command: >
      /bin/bash -c "sleep 30 && /opt/mssql-tools/bin/sqlcmd -S hospital-db -U sa -P ${SA_PASSWORD} -i /init.sql"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-web
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=hospital-db;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

volumes:
  hospitaldata:


      
