// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem.Core.Models;

public partial class PatientTreatment
{
    public int PatientId { get; set; }

    public int TreatmentId { get; set; }

    public DateOnly ObtainDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual Patient Patient { get; set; } = null!;

    public virtual Treatment Treatment { get; set; } = null!;
}