// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem.Core.Models;

public partial class Treatment
{
    public int TreatmentId { get; set; }

    public string TreatmentName { get; set; } = null!;

    public string? Description { get; set; }

    public virtual ICollection<PatientTreatment> PatientTreatments { get; set; } = new List<PatientTreatment>();
}